name: Deploy CryptoSniffer Bot to Amazon EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # - name: Connect EC2
      #   uses: easingthemes/ssh-deploy@v2.1.5
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      #     SOURCE: "./"
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.REMOTE_TARGET }}

      - name: echo
        env: 
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: echo $REMOTE_HOST - SSH
   
      - name: Git Clone
        run: ls
